/*
    note to contributors & developers that can read JSON:
        the extra commas are added at the end of each thing
        to help copy & pasting work better
        pleas dont remove them :)
*/
export default [
    {
        name: "Pen+",
        description: "Extended pen section! Adds blocks for drawing triangles using textures and tints, drawing images and editing their pixels, etc.",
        code: "ObviousAlexC/PenPlus.js",
        banner: "ObviousAlexC/PenPlus.svg",
        creator: "pinksheep2917",
    },
    {
        name: "Shovel Debugger",
        description: "Shovel's improved and feature rich debugger!",
        code: "TheShovel/shoveldebugger.js",
        banner: "TheShovel/thumbnail-shoveldebugger.avif",
        isGitHub: true,
        creator: "TheShovel",
    },
    {
        name: "Server Storage",
        description: "Similar to the server storage blocks in the 'Storage' extension, but with a better server uptime and non-global keys.\nDid you know the server is open source?",
        code: "Ikelene/serverStorageExtension.js",
        banner: "Ikelene/serverStorageIMG.avif",
        creator: "Ikelene",
        isGitHub: true,
    },
    {
        name: "Storage Plus",
        description: "A storage extension with many more features. Featuring server storage (with a fast server), local storage and more!",
        code: "Gen1x/storage_plus.js",
        banner: "Gen1x/storage_plus.avif",
        creator: "G1nX",
    },
    {
        name: "MotionSprite",
        description: "An advanced math-based animation system",
        code: "TheShovel/qoan-renderer.js",
        banner: "TheShovel/thumbnail-motionsprite.avif",
        isGitHub: true,
        creator: "TheShovel",
    },
    {
        name: "Boxed Physics",
        description: "Implements the Box2D physics engine into PenguinMod, adding joints, springs, etc. This is different from TurboWarp's implementation.",
        code: "pooiod/Box2D.js",
        banner: "pooiod/B2Dimg.svg",
        creator: "pooiod7",
    },
    {
        name: "Lighting",
        description: "A fast, powerful and easy-to-use lighting engine powered by WebGL!",
        code: "Gen1x/lighting.js",
        banner: "Gen1x/lighting.avif",
        creator: "G1nX",
        tags: ["new"],
    },
    {
        name: "3D Math",
        description: "A handful of utilities for making your own sprite-based 3D engine.",
        code: "ObviousAlexC/3DMath.js",
        banner: "ObviousAlexC/3DMath.svg",
        creator: "pinksheep2917",
    },
    {
        name: "GPU.sb3",
        description: "Use WebGPU compute shaders to accelerate your projects.",
        code: "derpygamer2142/gpusb3.js",
        banner: "derpygamer2142/gpusb3.svg",
        creator: "insanetaco2000",
        creatorAlias: "derpygamer2142",
        isGitHub: false,
        unstable: true,
        unstableReason: "WebGPU is still experimental and not supported by all browsers and does not work when packaged to electron. Check compatibility at webgpu.io."
    },
    {
        name: "Beat Sync",
        description: "An extension designed to let you sync anything in your project to a musical beat, with incredible precision.",
        code: "Gen1x/beat_sync.js",
        banner: "Gen1x/beat_sync.avif",
        creator: "G1nX",
    },
    {
        name: "Object",
        description: "Handle large JSON files at an extreme speed.",
        code: "skyhigh173/object.js",
        banner: "skyhigh173/object.svg",
        creator: "skyhigh173",
        isGitHub: true,
    },
    {
        name: "Scope Variable",
        description: "Manage your variables in a block-like structure.",
        code: "0znzw/ScopeVars.js",
        banner: "0znzw/ScopeVars.avif",
        creator: "yuri-kiss",
        isGitHub: true,
        unstable: true,
        unstableReason: "This extension uses unstable techniques that may not always work.",
    },
    {
        name: "Extra Timers",
        description: "Allows for the creation and management of additional timer blocks.",
        notes: "thumbnail by Dillon",
        code: "steve0greatness/timers.js",
        banner: "steve0greatness/timers.svg",
        creator: "Steve0Greatness",
        isGitHub: true, 
    },
    
    {
        name: "Dictation",
        description: "Convert your voice into text. (not supported in all browsers)",
        code: "pooiod/Dictation.js",
        banner: "pooiod/Dictation.svg",
        creator: "pooiod7",
    },
        {
        name: "Doodle Recognition",
        description: "A implementation of Google's Quick Draw image vision model",
        code: "TheShovel/doodlerec.js",
        banner: "TheShovel/thumbnail-doodlerec.avif",
        creator: "TheShovel",
        isGitHub: true,
    },
            {
        name: "Stylus",
        description: "Get the pressure and tilt of a stylus or graphic tablet",
        code: "sourdoggy/stylus extension.js",
        banner: "sourdoggy/stylus_ext.avif",
        creator: "sourdoggy",
        isGitHub: true,
    },
    {
        name: "Text To Speech: Redone",
        description: "A better alternitive to the base text to speech extension. Powered by the TTStool API",
        code: "PuzzlingGGG/ttsr.js",
        banner: "PuzzlingGGG/TTSR.avif",
        creator: "PuzzlingGGG",
        isGitHub: true,
    },
    {
        name: "CloudLink",
        description: "A powerful WebSocket extension for Scratch. Allows for online connectivity to servers for things like multiplayer.",
        code: "MikeDev101/cloudlink.js",
        banner: "MikeDev101/cloudlink.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "E2EE",
        description: "A general-purpose E2EE (End-to-End Encryption) extension for Scratch.",
        code: "MikeDev101/e2ee.js",
        banner: "MikeDev101/e2ee.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "WebRTC",
        description: "A barebones WebRTC implementation.",
        code: "MikeDev101/webrtc.js",
        banner: "MikeDev101/webrtc.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "Spritesheeter",
        description: "Load and manipulate spritesheets with customizable frames and XML support",
        code: "MubiLop/spritesheeter.js",
        banner: "MubiLop/spritesheeter.avif",
        creator: "cicerorph",
        creatorAlias: "MubiLop",
        isGitHub: true
    },
    {
        name: "Background Remover",
        description: "Removes background from images.",
        code: "dumzdev/removebg.js",
        banner: "dumzdev/removebgbanner.svg",
        creator: "dumzdev",
    },
    /*{
        name: "PenguinAI",
        description: "Talk to AI! Use Models like DALL-E-3, GPT, LLama, Claude, and more!",
        code: "MubiLop/penguingpt.js",
        banner: "MubiLop/penguingpt.avif",
        creator: "cicerorph",
        creatorAlias: "MubiLop",
        isGitHub: true,
        unstable: true,
        documentation: "PenguinAI",
        unstableReason: "AI models can generate unintended or inappropriate output.\nSome AI models may also become temporarily inaccessible.\n\nUse at your own risk.",
    },*/
/*
    {
        name: "Block AI",
        description: "An AI powered chat bot to help you code in your projects.",
        code: "TheShovel/blockAI.js",
        banner: "TheShovel/thumbnail-blockAI.avif",
        creator: "TheShovel",
        creatorAlias: "TheShovel",
        isGitHub: true,
        unstable: true,
        unstableReason: "The AI model can generate inaccurate output and broken syntax!",
    },
*/
    {
        name: "PenguinHook",
        description: "Send Webhook requests, that can be Discord or any type of webhook.",
        code: "MubiLop/penguinhook.js",
        banner: "MubiLop/penguinhook.avif",
        creator: "cicerorph",
        creatorAlias: "MubiLop",
        isGitHub: true,
    },
    {
        name: "Number Utilities",
        description: "Adds blocks for number formatting and manipulation.",
        code: "MubiLop/numutils.js",
        banner: "MubiLop/numutils.avif",
        creator: "cicerorph",
        creatorAlias: "MubiLop",
    },
    {
        name: "System Monitor",
        description: "Monitor GPU name, equivalency, and real-time network status.",
        code: "babys/babyssystemmonitor.js",
        banner: "babys/babyssystemmonitor.avif",
        creator: "babys",
        isGitHub: true,
    },
];
