/* 
    note to contributors & developers that can read JSON:
        the extra commas are added at the end of each thing
        to help copy & pasting work better
        pleas dont remove them :)
*/
export default [
    {
        name: "Pen+",
        description: "Extended pen section!",
        code: "ObviousAlexC/PenPlus.js",
        banner: "ObviousAlexC/PenPlus.svg",
        creator: "pinksheep2917",
    },
    {
        name: "3D Math",
        description: "A handful of utilities for making your own sprite-based 3D engine.",
        code: "ObviousAlexC/3DMath.js",
        banner: "ObviousAlexC/3DMath.svg",
        creator: "pinksheep2917",
    },
    {
        name: "Better Input",
        description: "Expansion to the Ask and Wait blocks.",
        code: "SharkPool/BetterInput.js",
        banner: "SharkPool/BetterInput.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sprite Parenting",
        description: "Link sprites together and make them follow the parent.",
        code: "SharkPool/Sprite-Linking.js",
        banner: "SharkPool/Sprite-Linking.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Particle Tools",
        description: "Tools for making particle engines easier.",
        documentation: "particle-tools",
        code: "SharkPool/Particle-Tools.js",
        banner: "SharkPool/Particle-Tools.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Tile Grids",
        description: "Place Sprites on Grids.",
        code: "SharkPool/Tile-Grids.js",
        banner: "SharkPool/Tile-Grids.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Better Storage",
        description: "Like PenguinMod's Storage Extension, but with a couple more features, and faster servers.",
        code: "Gen1x/better_storage.js",
        banner: "Gen1x/betterstorage.png",
        creator: "G1nX",
    },
    {
        name: "Mouth Washer",
        description: "Includes many utilities related to cleaning bad words, swearing and profanity.\nThought as an extra layer of security for chat projects.\n\n(ft. violet and jwklong)",
        code: "Gen1x/mouth_washer.js",
        banner: "Gen1x/mw-placeholder.png",
        creator: "G1nX",
    },
    {
        name: "Sound Waves",
        description: "Make sounds with oscillators!",
        code: "SharkPool/Sound-Waves.js",
        banner: "SharkPool/Sound-Waves.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Recording",
        description: "Record your voice while you run your projects!",
        code: "SharkPool/Recording.js",
        banner: "SharkPool/Recording.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "CORS Proxy",
        description: "Accessible CORS Proxies for fetching information",
        code: "NamelessCat/corsproxy.js",
        banner: "NamelessCat/corsproxy.png",
        creator: "NamelessCat",
    },
    {
        name: "CATS",
        description: "Blocks related to cats.",
        code: "Gen1x/CATS.js",
        banner: "Gen1x/cats.png",
        creator: "G1nX",
    },
    {
        name: "Extension Exposer",
        description: "Access the raw functions from other extensions.",
        code: "TheShovel/extexp.js",
        banner: "TheShovel/placeholder-extexp.png",
        creator: "TheShovel",
        isGitHub: true,
    },
    {
        name: "CloudLink",
        description: "A powerful WebSocket extension for Scratch.",
        code: "MikeDev101/cloudlink.js",
        banner: "MikeDev101/cloudlink.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "Mathematics",
        description: "Complicated maths extension for nerds.",
        code: "jwklong/mathematics.js",
        banner: "jwklong/mathematics.png",
        creator: "jwklong",
        isGitHub: true,
    },
    {
        name: "Twitch",
        description: "Communicate with your Twitch Chat on PenguinMod!\n\nPenguinMod is not affiliated with Twitch.",
        code: "bop_tw/Twitch.js",
        banner: "bop_tw/Twitch.png",
        creator: "bop_tw",
        isGitHub: false,
    },
];
