/* 
    note to contributors & developers that can read JSON:
        the extra commas are added at the end of each thing
        to help copy & pasting work better
        pleas dont remove them :)
*/
export default [
    {
        name: "TurboWeather",
        description: "Show weather and location data for any place in our world. Data that could be used for doxxing is deleted from results.",
        code: "RubyDevs/turboweather.js",
        banner: "RubyDevs/turboweather.webp",
        documentation: "TurboWeather",
        creator: "RubyDevs",
    },
    {
        name: "Object",
        description: "Handle large JSON files at an extreme speed.",
        code: "skyhigh173/object.js",
        banner: "skyhigh173/object.svg",
        creator: "skyhigh173",
        isGitHub: true,
    },
    {
        name: "Pen+",
        description: "Extended pen section!",
        code: "ObviousAlexC/PenPlus.js",
        banner: "ObviousAlexC/PenPlus.svg",
        creator: "pinksheep2917",
    },
    {
        name: "3D Math",
        description: "A handful of utilities for making your own sprite-based 3D engine.",
        code: "ObviousAlexC/3DMath.js",
        banner: "ObviousAlexC/3DMath.svg",
        creator: "pinksheep2917",
    },
    {
        name: "Sprite Effects",
        description: "Apply New Non-Vanilla Effects to Sprites and the Canvas!",
        code: "SharkPool/Sprite-Effects.js",
        banner: "SharkPool/Sprite-Effects.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Variables Expanded",
        description: "New Variable blocks and New Display Monitor types.\n(some contributions by DogeIsCut)",
        code: "SharkPool/Variables-Expanded.js",
        banner: "SharkPool/Variables-Expanded.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sty-Lists",
        description: "Customize and Organize Lists Monitors.",
        code: "SharkPool/Sty-Lists.js",
        banner: "SharkPool/Sty-Lists.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Display Text",
        description: "Display Advanced Text in Your Projects!",
        code: "SharkPool/Display-Text.js",
        banner: "SharkPool/Display-Text.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Better Input",
        description: "Expansion to the Ask and Wait blocks.",
        code: "SharkPool/BetterInput.js",
        banner: "SharkPool/BetterInput.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sprite Parenting",
        description: "Link sprites together and make them follow the parent.",
        code: "SharkPool/Sprite-Linking.js",
        banner: "SharkPool/Sprite-Linking.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Particle Tools",
        description: "Tools for making particle engines easier.",
        documentation: "particle-tools",
        code: "SharkPool/Particle-Tools.js",
        banner: "SharkPool/Particle-Tools.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Spotify API",
        description: "Fetch Statistics and Information and Play Songs from Spotify.",
        code: "SharkPool/Spotify.js",
        banner: "SharkPool/Spotify.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Speech Bubbles",
        description: "Customizable Speech Bubbles",
        code: "SharkPool/Speech-Bubbles.js",
        banner: "SharkPool/Speech-Bubbles.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Random Utilities",
        description: "Many blocks related to randomness.\nSome new features are seed-based number generation, true number generation, UUID's, random strings, etc.",
        code: "Gen1x/random_utils.js",
        banner: "Gen1x/randomutils.png",
        creator: "G1nX",
    },
    {
        name: "Tile Grids",
        description: "Place Sprites on Grids.",
        code: "SharkPool/Tile-Grids.js",
        banner: "SharkPool/Tile-Grids.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Animations",
        description: "Play Animations and Keyframes for your Sprites.",
        code: "SharkPool/Animations.js",
        banner: "SharkPool/Animations.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Time Calculations",
        description: "Blocks for calculating and converting time.",
        code: "SharkPool/Time-Calculations.js",
        banner: "SharkPool/Time-Calculations.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "How many lines?",
        description: "Blocks to determine the amount of new lines in a piece of text.",
        code: "Monochromasity/howmanylines.js",
        banner: "Monochromasity/placeholder-howmanylines.png",
        creator: "Monochromasity",
        isGitHub: true,
    },
    {
        name: "Free Servers",
        description: "Here you can find a free server for your projects. And also check whether it is working now or not.\n\nЗдесь вы можете найти бесплатный сервер для своих проектов. А также проверить, работает он сейчас или нет.",
        code: "WAYLIVES/FreeServers.js",
        banner: "WAYLIVES/FreeServersIMG.svg",
        documentation: "FreeServers",
        creator: "WAYLIVES",
        isGitHub: false,
    },
    {
        name: "Better Storage",
        description: "Like PenguinMod's Storage Extension, but with a couple more features, and faster servers.",
        code: "Gen1x/better_storage.js",
        banner: "Gen1x/betterstorage.png",
        creator: "G1nX",
    },
    {
        name: "Mouth Washer",
        description: "Includes many utilities related to cleaning bad words, swearing and profanity.\nThought as an extra layer of security for filtering messages.\n\n(ft. violet and jwklong)",
        code: "Gen1x/mouth_washer.js",
        banner: "Gen1x/mw-placeholder.png",
        creator: "G1nX",
    },
    {
        name: "All Menus",
        description: "Every dropdown menu for each block, in one extension.",
        code: "Lily/AllMenus.js",
        banner: "Lily/AllMenus.svg",
        creator: "LilyMakesThings",
        isGitHub: false,
    },
    {
        name: "Font Manager",
        description: "Manage, Create, and Delete Fonts.\n(Some Contributions by Ashimee)",
        code: "SharkPool/Font-Manager.js",
        banner: "SharkPool/Font-Manager.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sound Waves",
        description: "Make sounds with oscillators!",
        code: "SharkPool/Sound-Waves.js",
        banner: "SharkPool/Sound-Waves.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Recording",
        description: "Record your voice while you run your projects!",
        code: "SharkPool/Recording.js",
        banner: "SharkPool/Recording.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "CORS Proxy",
        description: "Accessible CORS Proxies for fetching information",
        code: "NamelessCat/corsproxy.js",
        banner: "NamelessCat/corsproxy.png",
        creator: "NamelessCat",
    },
    {
        name: "CATS",
        description: "Blocks related to cats.",
        code: "Gen1x/CATS.js",
        banner: "Gen1x/cats.png",
        creator: "G1nX",
    },
    {
        name: "Extension Exposer",
        description: "Access the raw functions from other extensions.",
        code: "TheShovel/extexp.js",
        banner: "TheShovel/placeholder-extexp.png",
        creator: "TheShovel",
        isGitHub: true,
    },
    {
        name: "CloudLink",
        description: "A powerful WebSocket extension for Scratch.",
        code: "MikeDev101/cloudlink.js",
        banner: "MikeDev101/cloudlink.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "Mathematics",
        description: "Complicated maths extension for nerds.",
        code: "jwklong/mathematics.js",
        banner: "jwklong/mathematics.png",
        creator: "jwklong",
        isGitHub: true,
    },
    {
        name: "Twitch",
        description: "Communicate with your Twitch Chat on PenguinMod!\n\nPenguinMod is not affiliated with Twitch.",
        code: "bop_tw/Twitch.js",
        banner: "bop_tw/Twitch.png",
        creator: "bop_tw",
        isGitHub: false,
    },
    {
        name: "Project Page",
        description: "How annoying can a extension possibly be? Modify and effect the project page from the code.",
        code: "jwklong/projectpage.js",
        banner: "jwklong/projectpage.png",
        creator: "jwklong",
        isGitHub: true,
    },
    {
        name: "Counter++",
        description: "Count anything, at any time, in Scratch!",
        code: "MrRedstonia/counterplusplus.js",
        banner: "MrRedstonia/counterplusplus.png",
        creator: "MrRedstonia",
        isGitHub: true,
    },
    {
        name: "Pang API",
        description: "Fetch information from the PenguinMod API.",
        code: "SammerLOL/pangapi.js",
        banner: "SammerLOL/pangapi.png",
        creator: "oc9x97",
        isGitHub: true,
    },
    {
        name: "Scope Variable",
        description: "Manage your variables in block like structure.",
        code: "0znzw/ScopeVars.js",
        banner: "0znzw/ScopeVars.png",
        creator: "Ashimee",
        isGitHub: true,
    },
];
