// ============================================================
//  3Dcamera — PenguinMod / TurboWarp Extension
//  A full software 3D renderer embedded in Scratch.
//  Author: generated by Replit Agent
//  Version: 1.0.0
//
//  Features:
//   • Full perspective projection pipeline
//   • Z-buffer (depth buffer) per-pixel
//   • Phong shading (ambient + diffuse + specular)
//   • Multiple primitive types: Box, Sphere, Plane, Cylinder, Pyramid, Cone
//   • Point lights, Directional lights, Ambient light
//   • Fog (linear / exponential)
//   • Skybox solid color or gradient
//   • Object transforms: position, rotation (Euler), scale
//   • Materials: color, shininess, wireframe mode
//   • Raycasting: world-space ray from screen pixel
//   • Object hit detection (bounding-sphere)
//   • Camera: position, yaw/pitch/roll, FOV, near/far
//   • 3-D point projection → 2-D screen coordinate
//   • Render-quality control (pixel size)
//   • Object visibility toggle
//   • Delete objects by name
//   • 20+ blocks in total
// ============================================================

(function (Scratch) {
  'use strict';

  // ============================================================
  // §1  MATH LIBRARY
  // ============================================================

  const DEG = Math.PI / 180;

  // ── Vec3 ──────────────────────────────────────────────────
  class Vec3 {
    constructor(x = 0, y = 0, z = 0) { this.x = x; this.y = y; this.z = z; }

    clone()           { return new Vec3(this.x, this.y, this.z); }
    add(v)            { return new Vec3(this.x + v.x, this.y + v.y, this.z + v.z); }
    sub(v)            { return new Vec3(this.x - v.x, this.y - v.y, this.z - v.z); }
    mul(s)            { return new Vec3(this.x * s,   this.y * s,   this.z * s);   }
    div(s)            { return new Vec3(this.x / s,   this.y / s,   this.z / s);   }
    dot(v)            { return this.x * v.x + this.y * v.y + this.z * v.z; }
    lengthSq()        { return this.dot(this); }
    length()          { return Math.sqrt(this.lengthSq()); }
    normalize()       { const l = this.length(); return l > 1e-8 ? this.div(l) : new Vec3(0,1,0); }
    negate()          { return new Vec3(-this.x, -this.y, -this.z); }
    cross(v) {
      return new Vec3(
        this.y * v.z - this.z * v.y,
        this.z * v.x - this.x * v.z,
        this.x * v.y - this.y * v.x
      );
    }
    lerp(v, t)        { return this.add(v.sub(this).mul(t)); }
    static fromArray(a) { return new Vec3(a[0], a[1], a[2]); }
    toArray()          { return [this.x, this.y, this.z]; }
  }

  // ── Vec4 ──────────────────────────────────────────────────
  class Vec4 {
    constructor(x = 0, y = 0, z = 0, w = 1) { this.x = x; this.y = y; this.z = z; this.w = w; }
    toVec3() { return new Vec3(this.x, this.y, this.z); }
  }

  // ── Mat4 (column-major) ───────────────────────────────────
  class Mat4 {
    constructor() { this.m = new Float64Array(16); this.identity(); }

    identity() {
      const m = this.m;
      m[0]=1; m[4]=0; m[8]=0;  m[12]=0;
      m[1]=0; m[5]=1; m[9]=0;  m[13]=0;
      m[2]=0; m[6]=0; m[10]=1; m[14]=0;
      m[3]=0; m[7]=0; m[11]=0; m[15]=1;
      return this;
    }

    static identity() { return new Mat4(); }

    static translation(x, y, z) {
      const r = new Mat4();
      r.m[12] = x; r.m[13] = y; r.m[14] = z;
      return r;
    }

    static scale(x, y, z) {
      const r = new Mat4();
      r.m[0] = x; r.m[5] = y; r.m[10] = z;
      return r;
    }

    static rotationX(a) {
      const r = new Mat4();
      const c = Math.cos(a), s = Math.sin(a);
      r.m[5]=c; r.m[6]=s; r.m[9]=-s; r.m[10]=c;
      return r;
    }

    static rotationY(a) {
      const r = new Mat4();
      const c = Math.cos(a), s = Math.sin(a);
      r.m[0]=c; r.m[2]=-s; r.m[8]=s; r.m[10]=c;
      return r;
    }

    static rotationZ(a) {
      const r = new Mat4();
      const c = Math.cos(a), s = Math.sin(a);
      r.m[0]=c; r.m[1]=s; r.m[4]=-s; r.m[5]=c;
      return r;
    }

    mul(b) {
      const r = new Mat4();
      const a = this.m, bm = b.m, rm = r.m;
      for (let row = 0; row < 4; row++) {
        for (let col = 0; col < 4; col++) {
          let sum = 0;
          for (let k = 0; k < 4; k++) {
            sum += a[k * 4 + row] * bm[col * 4 + k];
          }
          rm[col * 4 + row] = sum;
        }
      }
      return r;
    }

    mulVec4(v) {
      const m = this.m;
      return new Vec4(
        m[0]*v.x + m[4]*v.y + m[8]*v.z  + m[12]*v.w,
        m[1]*v.x + m[5]*v.y + m[9]*v.z  + m[13]*v.w,
        m[2]*v.x + m[6]*v.y + m[10]*v.z + m[14]*v.w,
        m[3]*v.x + m[7]*v.y + m[11]*v.z + m[15]*v.w
      );
    }

    mulVec3(v) {
      const r = this.mulVec4(new Vec4(v.x, v.y, v.z, 1));
      return new Vec3(r.x, r.y, r.z);
    }

    mulDir(v) {
      const r = this.mulVec4(new Vec4(v.x, v.y, v.z, 0));
      return new Vec3(r.x, r.y, r.z);
    }

    transpose() {
      const r = new Mat4(), m = this.m, rm = r.m;
      for (let i = 0; i < 4; i++)
        for (let j = 0; j < 4; j++)
          rm[j * 4 + i] = m[i * 4 + j];
      return r;
    }

    static perspective(fovY, aspect, near, far) {
      const r = new Mat4();
      const f = 1.0 / Math.tan(fovY * 0.5);
      const nf = 1.0 / (near - far);
      r.m[0]  = f / aspect;
      r.m[5]  = f;
      r.m[10] = (far + near) * nf;
      r.m[11] = -1;
      r.m[14] = 2 * far * near * nf;
      r.m[15] = 0;
      return r;
    }

    static lookAt(eye, center, up) {
      const f = center.sub(eye).normalize();
      const s = f.cross(up).normalize();
      const u = s.cross(f);
      const r = new Mat4();
      const m = r.m;
      m[0]=s.x;  m[4]=s.y;  m[8]=s.z;   m[12]=-s.dot(eye);
      m[1]=u.x;  m[5]=u.y;  m[9]=u.z;   m[13]=-u.dot(eye);
      m[2]=-f.x; m[6]=-f.y; m[10]=-f.z; m[14]=f.dot(eye);
      m[15]=1;
      return r;
    }

    inverse() {
      // 4x4 inverse via cofactors
      const m = this.m, inv = new Float64Array(16);
      inv[0]  =  m[5]*m[10]*m[15] - m[5]*m[11]*m[14] - m[9]*m[6]*m[15] + m[9]*m[7]*m[14] + m[13]*m[6]*m[11] - m[13]*m[7]*m[10];
      inv[4]  = -m[4]*m[10]*m[15] + m[4]*m[11]*m[14] + m[8]*m[6]*m[15] - m[8]*m[7]*m[14] - m[12]*m[6]*m[11] + m[12]*m[7]*m[10];
      inv[8]  =  m[4]*m[9]*m[15]  - m[4]*m[11]*m[13] - m[8]*m[5]*m[15] + m[8]*m[7]*m[13] + m[12]*m[5]*m[11] - m[12]*m[7]*m[9];
      inv[12] = -m[4]*m[9]*m[14]  + m[4]*m[10]*m[13] + m[8]*m[5]*m[14] - m[8]*m[6]*m[13] - m[12]*m[5]*m[10] + m[12]*m[6]*m[9];
      inv[1]  = -m[1]*m[10]*m[15] + m[1]*m[11]*m[14] + m[9]*m[2]*m[15] - m[9]*m[3]*m[14] - m[13]*m[2]*m[11] + m[13]*m[3]*m[10];
      inv[5]  =  m[0]*m[10]*m[15] - m[0]*m[11]*m[14] - m[8]*m[2]*m[15] + m[8]*m[3]*m[14] + m[12]*m[2]*m[11] - m[12]*m[3]*m[10];
      inv[9]  = -m[0]*m[9]*m[15]  + m[0]*m[11]*m[13] + m[8]*m[1]*m[15] - m[8]*m[3]*m[13] - m[12]*m[1]*m[11] + m[12]*m[3]*m[9];
      inv[13] =  m[0]*m[9]*m[14]  - m[0]*m[10]*m[13] - m[8]*m[1]*m[14] + m[8]*m[2]*m[13] + m[12]*m[1]*m[10] - m[12]*m[2]*m[9];
      inv[2]  =  m[1]*m[6]*m[15]  - m[1]*m[7]*m[14]  - m[5]*m[2]*m[15] + m[5]*m[3]*m[14] + m[13]*m[2]*m[7]  - m[13]*m[3]*m[6];
      inv[6]  = -m[0]*m[6]*m[15]  + m[0]*m[7]*m[14]  + m[4]*m[2]*m[15] - m[4]*m[3]*m[14] - m[12]*m[2]*m[7]  + m[12]*m[3]*m[6];
      inv[10] =  m[0]*m[5]*m[15]  - m[0]*m[7]*m[13]  - m[4]*m[1]*m[15] + m[4]*m[3]*m[13] + m[12]*m[1]*m[7]  - m[12]*m[3]*m[5];
      inv[14] = -m[0]*m[5]*m[14]  + m[0]*m[6]*m[13]  + m[4]*m[1]*m[14] - m[4]*m[2]*m[13] - m[12]*m[1]*m[6]  + m[12]*m[2]*m[5];
      inv[3]  = -m[1]*m[6]*m[11]  + m[1]*m[7]*m[10]  + m[5]*m[2]*m[11] - m[5]*m[3]*m[10] - m[9]*m[2]*m[7]   + m[9]*m[3]*m[6];
      inv[7]  =  m[0]*m[6]*m[11]  - m[0]*m[7]*m[10]  - m[4]*m[2]*m[11] + m[4]*m[3]*m[10] + m[8]*m[2]*m[7]   - m[8]*m[3]*m[6];
      inv[11] = -m[0]*m[5]*m[11]  + m[0]*m[7]*m[9]   + m[4]*m[1]*m[11] - m[4]*m[3]*m[9]  - m[8]*m[1]*m[7]   + m[8]*m[3]*m[5];
      inv[15] =  m[0]*m[5]*m[10]  - m[0]*m[6]*m[9]   - m[4]*m[1]*m[10] + m[4]*m[2]*m[9]  + m[8]*m[1]*m[6]   - m[8]*m[2]*m[5];
      let det = m[0]*inv[0] + m[1]*inv[4] + m[2]*inv[8] + m[3]*inv[12];
      if (Math.abs(det) < 1e-12) return Mat4.identity();
      det = 1.0 / det;
      const res = new Mat4();
      for (let i = 0; i < 16; i++) res.m[i] = inv[i] * det;
      return res;
    }
  }

  // ── Color helpers ─────────────────────────────────────────
  function hexToRgb(hex) {
    hex = hex.replace(/^#/, '');
    if (hex.length === 3) hex = hex.split('').map(c=>c+c).join('');
    const n = parseInt(hex, 16);
    return { r: (n >> 16) & 0xff, g: (n >> 8) & 0xff, b: n & 0xff };
  }

  function clamp01(v) { return Math.max(0, Math.min(1, v)); }
  function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

  // ============================================================
  // §2  GEOMETRY GENERATION
  // ============================================================

  // Each primitive returns { vertices: Vec3[], normals: Vec3[], triangles: [i,i,i][] }

  function genBox(w = 1, h = 1, d = 1) {
    const hw = w/2, hh = h/2, hd = d/2;
    const verts = [
      // front
      new Vec3(-hw,-hh, hd), new Vec3( hw,-hh, hd), new Vec3( hw, hh, hd), new Vec3(-hw, hh, hd),
      // back
      new Vec3( hw,-hh,-hd), new Vec3(-hw,-hh,-hd), new Vec3(-hw, hh,-hd), new Vec3( hw, hh,-hd),
      // left
      new Vec3(-hw,-hh,-hd), new Vec3(-hw,-hh, hd), new Vec3(-hw, hh, hd), new Vec3(-hw, hh,-hd),
      // right
      new Vec3( hw,-hh, hd), new Vec3( hw,-hh,-hd), new Vec3( hw, hh,-hd), new Vec3( hw, hh, hd),
      // top
      new Vec3(-hw, hh, hd), new Vec3( hw, hh, hd), new Vec3( hw, hh,-hd), new Vec3(-hw, hh,-hd),
      // bottom
      new Vec3(-hw,-hh,-hd), new Vec3( hw,-hh,-hd), new Vec3( hw,-hh, hd), new Vec3(-hw,-hh, hd),
    ];
    const faceNormals = [
      new Vec3(0,0,1), new Vec3(0,0,-1),
      new Vec3(-1,0,0), new Vec3(1,0,0),
      new Vec3(0,1,0), new Vec3(0,-1,0)
    ];
    const normals = [];
    for (let f=0; f<6; f++) for (let i=0; i<4; i++) normals.push(faceNormals[f].clone());
    const tris = [];
    for (let f=0; f<6; f++) {
      const b = f*4;
      tris.push([b,b+1,b+2], [b,b+2,b+3]);
    }
    return { vertices: verts, normals, triangles: tris };
  }

  function genSphere(r = 0.5, latSegs = 12, lonSegs = 16) {
    const verts = [], normals = [], tris = [];
    for (let lat = 0; lat <= latSegs; lat++) {
      const theta = lat * Math.PI / latSegs;
      const sinT = Math.sin(theta), cosT = Math.cos(theta);
      for (let lon = 0; lon <= lonSegs; lon++) {
        const phi = lon * 2 * Math.PI / lonSegs;
        const sinP = Math.sin(phi), cosP = Math.cos(phi);
        const n = new Vec3(sinT*cosP, cosT, sinT*sinP);
        normals.push(n);
        verts.push(n.mul(r));
      }
    }
    for (let lat = 0; lat < latSegs; lat++) {
      for (let lon = 0; lon < lonSegs; lon++) {
        const a = lat*(lonSegs+1)+lon;
        const b = a+lonSegs+1;
        tris.push([a, b, a+1]);
        tris.push([b, b+1, a+1]);
      }
    }
    return { vertices: verts, normals, triangles: tris };
  }

  function genPlane(w = 2, d = 2, segsW = 4, segsD = 4) {
    const verts = [], normals = [], tris = [];
    for (let iz = 0; iz <= segsD; iz++) {
      for (let ix = 0; ix <= segsW; ix++) {
        const x = (ix/segsW - 0.5)*w;
        const z = (iz/segsD - 0.5)*d;
        verts.push(new Vec3(x, 0, z));
        normals.push(new Vec3(0, 1, 0));
      }
    }
    const stride = segsW+1;
    for (let iz = 0; iz < segsD; iz++) {
      for (let ix = 0; ix < segsW; ix++) {
        const a = iz*stride+ix, b = a+stride;
        tris.push([a, b, a+1]);
        tris.push([b, b+1, a+1]);
      }
    }
    return { vertices: verts, normals, triangles: tris };
  }

  function genCylinder(r = 0.5, h = 1, segs = 16) {
    const verts = [], normals = [], tris = [];
    const hh = h/2;
    // side
    for (let i = 0; i <= segs; i++) {
      const a = i/segs * 2*Math.PI;
      const cos = Math.cos(a), sin = Math.sin(a);
      verts.push(new Vec3(cos*r, -hh, sin*r));
      normals.push(new Vec3(cos, 0, sin));
      verts.push(new Vec3(cos*r,  hh, sin*r));
      normals.push(new Vec3(cos, 0, sin));
    }
    for (let i = 0; i < segs; i++) {
      const b = i*2;
      tris.push([b,b+2,b+1]); tris.push([b+1,b+2,b+3]);
    }
    // caps
    const capBase = verts.length;
    // bottom cap center
    verts.push(new Vec3(0,-hh,0)); normals.push(new Vec3(0,-1,0));
    const bCenter = verts.length - 1;
    for (let i = 0; i <= segs; i++) {
      const a = i/segs*2*Math.PI;
      verts.push(new Vec3(Math.cos(a)*r, -hh, Math.sin(a)*r));
      normals.push(new Vec3(0,-1,0));
    }
    for (let i = 0; i < segs; i++) tris.push([bCenter, bCenter+1+i+1, bCenter+1+i]);
    // top cap center
    verts.push(new Vec3(0,hh,0)); normals.push(new Vec3(0,1,0));
    const tCenter = verts.length - 1;
    for (let i = 0; i <= segs; i++) {
      const a = i/segs*2*Math.PI;
      verts.push(new Vec3(Math.cos(a)*r, hh, Math.sin(a)*r));
      normals.push(new Vec3(0,1,0));
    }
    for (let i = 0; i < segs; i++) tris.push([tCenter, tCenter+1+i, tCenter+1+i+1]);
    return { vertices: verts, normals, triangles: tris };
  }

  function genPyramid(r = 0.5, h = 1, segs = 4) {
    const verts = [], normals = [], tris = [];
    const apex = new Vec3(0, h, 0);
    const base = [];
    for (let i = 0; i < segs; i++) {
      const a = i/segs*2*Math.PI;
      base.push(new Vec3(Math.cos(a)*r, 0, Math.sin(a)*r));
    }
    // side faces
    for (let i = 0; i < segs; i++) {
      const a = base[i], b = base[(i+1)%segs];
      const edge1 = b.sub(a), edge2 = apex.sub(a);
      const n = edge1.cross(edge2).normalize();
      const vi = verts.length;
      verts.push(a.clone(), b.clone(), apex.clone());
      normals.push(n, n, n);
      tris.push([vi, vi+1, vi+2]);
    }
    // base
    const center = new Vec3(0,0,0);
    for (let i = 0; i < segs; i++) {
      const a = base[i], b = base[(i+1)%segs];
      const vi = verts.length;
      verts.push(center.clone(), b.clone(), a.clone());
      normals.push(new Vec3(0,-1,0), new Vec3(0,-1,0), new Vec3(0,-1,0));
      tris.push([vi, vi+1, vi+2]);
    }
    return { vertices: verts, normals, triangles: tris };
  }

  function genCone(r = 0.5, h = 1, segs = 16) {
    const verts = [], normals = [], tris = [];
    const apex = new Vec3(0, h, 0);
    // side
    for (let i = 0; i < segs; i++) {
      const a0 = i/segs*2*Math.PI, a1 = (i+1)/segs*2*Math.PI;
      const p0 = new Vec3(Math.cos(a0)*r, 0, Math.sin(a0)*r);
      const p1 = new Vec3(Math.cos(a1)*r, 0, Math.sin(a1)*r);
      const n = p0.add(p1).mul(0.5).normalize();
      const vi = verts.length;
      verts.push(p0.clone(), p1.clone(), apex.clone());
      normals.push(n, n, new Vec3(0,1,0));
      tris.push([vi, vi+1, vi+2]);
    }
    // base cap
    const center = new Vec3(0,0,0);
    for (let i = 0; i < segs; i++) {
      const a0 = i/segs*2*Math.PI, a1 = (i+1)/segs*2*Math.PI;
      const vi = verts.length;
      verts.push(center.clone(), new Vec3(Math.cos(a1)*r,0,Math.sin(a1)*r), new Vec3(Math.cos(a0)*r,0,Math.sin(a0)*r));
      normals.push(new Vec3(0,-1,0), new Vec3(0,-1,0), new Vec3(0,-1,0));
      tris.push([vi, vi+1, vi+2]);
    }
    return { vertices: verts, normals, triangles: tris };
  }

  // ============================================================
  // §3  SCENE OBJECTS
  // ============================================================

  class Material {
    constructor(color = '#ff8800', shininess = 32, wireframe = false) {
      const c = hexToRgb(color);
      this.r = c.r / 255;
      this.g = c.g / 255;
      this.b = c.b / 255;
      this.shininess = shininess;
      this.wireframe = wireframe;
      this.opacity = 1.0;
    }
    setColor(hex) {
      const c = hexToRgb(hex);
      this.r = c.r/255; this.g = c.g/255; this.b = c.b/255;
    }
  }

  class SceneObject {
    constructor(name, geometry, material) {
      this.name      = name;
      this.geometry  = geometry;       // { vertices, normals, triangles }
      this.material  = material;
      this.position  = new Vec3(0,0,0);
      this.rotation  = new Vec3(0,0,0); // Euler degrees: pitch, yaw, roll
      this.scale     = new Vec3(1,1,1);
      this.visible   = true;
      this._worldVerts   = null;
      this._worldNormals = null;
      this._dirty    = true;
      // bounding sphere radius (object space, no scale)
      let maxR = 0;
      for (const v of geometry.vertices) { const l = v.length(); if (l > maxR) maxR = l; }
      this.boundingSphereR = maxR;
    }

    modelMatrix() {
      const T  = Mat4.translation(this.position.x, this.position.y, this.position.z);
      const Rx = Mat4.rotationX(this.rotation.x * DEG);
      const Ry = Mat4.rotationY(this.rotation.y * DEG);
      const Rz = Mat4.rotationZ(this.rotation.z * DEG);
      const S  = Mat4.scale(this.scale.x, this.scale.y, this.scale.z);
      return T.mul(Ry).mul(Rx).mul(Rz).mul(S);
    }

    buildWorldGeometry() {
      const M  = this.modelMatrix();
      // normal matrix = transpose(inverse(M)) — for non-uniform scale
      const NM = M.inverse().transpose();
      this._worldVerts   = this.geometry.vertices.map(v  => M.mulVec3(v));
      this._worldNormals = this.geometry.normals.map(n => NM.mulDir(n).normalize());
      this._dirty = false;
    }

    worldCenter() {
      return this.position.clone();
    }
  }

  class PointLight {
    constructor(name, position, color, intensity, range) {
      this.name      = name;
      this.position  = position;
      this.color     = hexToRgb(color);
      this.intensity = intensity;
      this.range     = range;
      this.on        = true;
    }
  }

  class DirectionalLight {
    constructor(name, direction, color, intensity) {
      this.name      = name;
      this.direction = direction.normalize();
      this.color     = hexToRgb(color);
      this.intensity = intensity;
      this.on        = true;
    }
  }

  // ============================================================
  // §4  CAMERA
  // ============================================================

  class Camera {
    constructor() {
      this.position = new Vec3(0, 1, 5);
      this.yaw   = 0;   // degrees, horizontal rotation
      this.pitch = 0;   // degrees, vertical tilt
      this.roll  = 0;   // degrees, roll
      this.fov   = 60;  // degrees, vertical FOV
      this.near  = 0.1;
      this.far   = 500;
    }

    forward() {
      return new Vec3(
        Math.sin(this.yaw*DEG) * Math.cos(this.pitch*DEG),
        Math.sin(-this.pitch*DEG),
        -Math.cos(this.yaw*DEG) * Math.cos(this.pitch*DEG)
      ).normalize();
    }

    right() { return this.forward().cross(new Vec3(0,1,0)).normalize(); }
    up()    { return this.right().cross(this.forward()).normalize(); }

    viewMatrix() {
      const f = this.forward();
      const target = this.position.add(f);
      const upRef  = new Vec3(
        Math.sin(this.roll*DEG)*Math.cos(this.yaw*DEG - Math.PI/2),
        Math.cos(this.roll*DEG),
        Math.sin(this.roll*DEG)*Math.sin(this.yaw*DEG - Math.PI/2)
      );
      return Mat4.lookAt(this.position, target, new Vec3(0,1,0).add(upRef.mul(Math.sin(this.roll*DEG)*0.1)).normalize());
    }

    projMatrix(aspect) {
      return Mat4.perspective(this.fov*DEG, aspect, this.near, this.far);
    }

    moveForward(dist)  { this.position = this.position.add(this.forward().mul(dist)); }
    moveRight(dist)    { this.position = this.position.add(this.right().mul(dist)); }
    moveUp(dist)       { this.position = this.position.add(new Vec3(0, dist, 0)); }
  }

  // ============================================================
  // §5  SOFTWARE RASTERIZER
  // ============================================================

  class Renderer {
    constructor(width, height) {
      this.width  = width;
      this.height = height;
      this.pixels = new Uint8ClampedArray(width * height * 4);
      this.depth  = new Float64Array(width * height).fill(Infinity);
      this.skyTop    = { r: 30,  g: 60,  b: 120 };
      this.skyBottom = { r: 120, g: 170, b: 220 };
      this.fogEnabled = false;
      this.fogColor   = { r: 200, g: 200, b: 200 };
      this.fogNear    = 10;
      this.fogFar     = 80;
      this.fogExp     = false;
      this.quality    = 2; // pixel block size (1=full, 2=half res, etc.)
      this.ambient    = { r: 0.15, g: 0.15, b: 0.15 };
    }

    resize(w, h) {
      this.width  = w; this.height = h;
      this.pixels = new Uint8ClampedArray(w * h * 4);
      this.depth  = new Float64Array(w * h).fill(Infinity);
    }

    clear() {
      // draw sky gradient
      const W = this.width, H = this.height;
      const pix = this.pixels;
      for (let y = 0; y < H; y++) {
        const t = y / (H - 1);
        const r = this.skyTop.r + (this.skyBottom.r - this.skyTop.r) * t;
        const g = this.skyTop.g + (this.skyBottom.g - this.skyTop.g) * t;
        const b = this.skyTop.b + (this.skyBottom.b - this.skyTop.b) * t;
        for (let x = 0; x < W; x++) {
          const i = (y*W + x) * 4;
          pix[i]   = r; pix[i+1] = g; pix[i+2] = b; pix[i+3] = 255;
        }
      }
      this.depth.fill(Infinity);
    }

    setPixel(x, y, depth, cr, cg, cb) {
      x = x | 0; y = y | 0;
      if (x < 0 || x >= this.width || y < 0 || y >= this.height) return;
      const idx = y * this.width + x;
      if (depth >= this.depth[idx]) return;
      this.depth[idx] = depth;
      const pi = idx * 4;
      this.pixels[pi]   = clamp(cr*255, 0, 255) | 0;
      this.pixels[pi+1] = clamp(cg*255, 0, 255) | 0;
      this.pixels[pi+2] = clamp(cb*255, 0, 255) | 0;
      this.pixels[pi+3] = 255;
    }

    // Barycentric triangle rasterizer with depth interpolation + Phong shading
    drawTriangle(
      p0, p1, p2,          // {x,y,z} screen coords (z=ndc depth)
      n0, n1, n2,          // world normals
      w0, w1, w2,          // world positions Vec3
      mat,                 // Material
      lights,              // array of lights
      camPos               // Vec3 camera position
    ) {
      const minX = Math.max(0, Math.floor(Math.min(p0.x, p1.x, p2.x)));
      const maxX = Math.min(this.width  - 1, Math.ceil(Math.max(p0.x, p1.x, p2.x)));
      const minY = Math.max(0, Math.floor(Math.min(p0.y, p1.y, p2.y)));
      const maxY = Math.min(this.height - 1, Math.ceil(Math.max(p0.y, p1.y, p2.y)));

      const dX01 = p1.x - p0.x, dY01 = p1.y - p0.y;
      const dX12 = p2.x - p1.x, dY12 = p2.y - p1.y;
      const dX20 = p0.x - p2.x, dY20 = p0.y - p2.y;
      const area = dX01*dY20 - dY01*dX20;
      if (Math.abs(area) < 0.5) return;

      const invArea = 1 / area;

      for (let py = minY; py <= maxY; py++) {
        for (let px = minX; px <= maxX; px++) {
          const cx = px + 0.5, cy = py + 0.5;
          let b0 = ((cx - p1.x)*dY12 - (cy - p1.y)*dX12) * invArea;
          let b1 = ((cx - p2.x)*dY20 - (cy - p2.y)*dX20) * invArea;
          let b2 = 1 - b0 - b1;
          if (b0 < 0 || b1 < 0 || b2 < 0) continue;

          const depth = p0.z*b0 + p1.z*b1 + p2.z*b2;
          if (depth < -1 || depth > 1) continue;

          // interpolate world position
          const wx = w0.x*b0 + w1.x*b1 + w2.x*b2;
          const wy = w0.y*b0 + w1.y*b1 + w2.y*b2;
          const wz = w0.z*b0 + w1.z*b1 + w2.z*b2;

          // interpolate normal
          let nx = n0.x*b0 + n1.x*b1 + n2.x*b2;
          let ny = n0.y*b0 + n1.y*b1 + n2.y*b2;
          let nz = n0.z*b0 + n1.z*b1 + n2.z*b2;
          const nl = Math.sqrt(nx*nx+ny*ny+nz*nz);
          if (nl > 1e-8) { nx/=nl; ny/=nl; nz/=nl; }

          // Phong lighting
          let litR = this.ambient.r * mat.r;
          let litG = this.ambient.g * mat.g;
          let litB = this.ambient.b * mat.b;

          const vx = camPos.x-wx, vy = camPos.y-wy, vz = camPos.z-wz;
          const vl = Math.sqrt(vx*vx+vy*vy+vz*vz);
          const vnx = vl>1e-8?vx/vl:0, vny = vl>1e-8?vy/vl:0, vnz = vl>1e-8?vz/vl:0;

          for (const light of lights) {
            if (!light.on) continue;

            let lx, ly, lz, atten = 1;

            if (light instanceof PointLight) {
              lx = light.position.x - wx;
              ly = light.position.y - wy;
              lz = light.position.z - wz;
              const dist = Math.sqrt(lx*lx+ly*ly+lz*lz);
              if (dist < 1e-8) continue;
              lx/=dist; ly/=dist; lz/=dist;
              atten = Math.max(0, 1 - dist/light.range);
            } else {
              // directional
              lx = -light.direction.x;
              ly = -light.direction.y;
              lz = -light.direction.z;
            }

            const diff = Math.max(0, nx*lx + ny*ly + nz*lz);
            const cr = light.color.r/255, cg = light.color.g/255, cb = light.color.b/255;
            const intensity = light.intensity * atten;

            litR += mat.r * diff * cr * intensity;
            litG += mat.g * diff * cg * intensity;
            litB += mat.b * diff * cb * intensity;

            // specular
            const rx = lx - 2*(nx*lx+ny*ly+nz*lz)*nx;
            const ry = ly - 2*(nx*lx+ny*ly+nz*lz)*ny;
            const rz = lz - 2*(nx*lx+ny*ly+nz*lz)*nz;
            const spec = Math.max(0, rx*vnx+ry*vny+rz*vnz);
            const specPow = Math.pow(spec, mat.shininess) * intensity;
            litR += specPow * cr;
            litG += specPow * cg;
            litB += specPow * cb;
          }

          // fog
          if (this.fogEnabled) {
            const dist = Math.sqrt((wx-camPos.x)**2+(wy-camPos.y)**2+(wz-camPos.z)**2);
            let fogFactor;
            if (this.fogExp) {
              fogFactor = 1 - Math.exp(-dist/this.fogFar);
            } else {
              fogFactor = clamp01((dist - this.fogNear)/(this.fogFar - this.fogNear));
            }
            const fr=this.fogColor.r/255, fg=this.fogColor.g/255, fb=this.fogColor.b/255;
            litR = litR*(1-fogFactor) + fr*fogFactor;
            litG = litG*(1-fogFactor) + fg*fogFactor;
            litB = litB*(1-fogFactor) + fb*fogFactor;
          }

          const q = this.quality;
          if (q <= 1) {
            this.setPixel(px, py, depth, litR, litG, litB);
          } else {
            for (let dy = 0; dy < q; dy++)
              for (let dx = 0; dx < q; dx++)
                this.setPixel(px*q+dx, py*q+dy, depth, litR, litG, litB);
          }
        }
      }
    }

    drawWireframeTriangle(p0, p1, p2, r, g, b) {
      this.drawLine(p0, p1, r, g, b);
      this.drawLine(p1, p2, r, g, b);
      this.drawLine(p2, p0, r, g, b);
    }

    drawLine(p0, p1, r, g, b) {
      let x0=p0.x|0, y0=p0.y|0, z0=p0.z;
      let x1=p1.x|0, y1=p1.y|0, z1=p1.z;
      const dx=Math.abs(x1-x0), dy=Math.abs(y1-y0);
      const steps=Math.max(dx,dy,1);
      for (let i=0;i<=steps;i++) {
        const t=i/steps;
        const x=Math.round(x0+(x1-x0)*t);
        const y=Math.round(y0+(y1-y0)*t);
        const z=z0+(z1-z0)*t;
        this.setPixel(x,y,z,r,g,b);
      }
    }
  }

  // ============================================================
  // §6  SCENE & RENDER PIPELINE
  // ============================================================

  class Scene {
    constructor() {
      this.objects  = [];   // SceneObject[]
      this.lights   = [];   // PointLight | DirectionalLight
      this.camera   = new Camera();
      this.renderer = new Renderer(1, 1); // will be resized
      this.lastHitName = '';
      this.lastProjected = { x: 0, y: 0 };
    }

    findObject(name) { return this.objects.find(o => o.name === name) || null; }
    findLight(name)  { return this.lights.find(l => l.name === name)  || null; }

    addObject(name, type, params, colorHex, shininess) {
      let geo;
      switch (type.toLowerCase()) {
        case 'box':      geo = genBox(params[0]||1, params[1]||1, params[2]||1); break;
        case 'sphere':   geo = genSphere(params[0]||0.5); break;
        case 'plane':    geo = genPlane(params[0]||4, params[1]||4); break;
        case 'cylinder': geo = genCylinder(params[0]||0.5, params[1]||1); break;
        case 'pyramid':  geo = genPyramid(params[0]||0.5, params[1]||1); break;
        case 'cone':     geo = genCone(params[0]||0.5, params[1]||1); break;
        default:         geo = genBox(1,1,1);
      }
      const mat = new Material(colorHex || '#ff8800', shininess || 32);
      const obj = new SceneObject(name, geo, mat);
      this.objects.push(obj);
      return obj;
    }

    removeObject(name) {
      const idx = this.objects.findIndex(o => o.name === name);
      if (idx !== -1) this.objects.splice(idx, 1);
    }

    // Project a 3D world point to 2D screen (returns pixel x,y)
    projectPoint(worldPos, W, H) {
      const V = this.camera.viewMatrix();
      const P = this.camera.projMatrix(W/H);
      const vp = V.mulVec4(new Vec4(worldPos.x, worldPos.y, worldPos.z, 1));
      const clip = P.mulVec4(vp);
      if (Math.abs(clip.w) < 1e-6) return null;
      const ndcX = clip.x/clip.w, ndcY = clip.y/clip.w;
      return {
        x: (ndcX*0.5+0.5)*W,
        y: (1-(ndcY*0.5+0.5))*H
      };
    }

    // Ray from screen pixel
    screenRay(px, py, W, H) {
      const ndcX = (px/W)*2-1;
      const ndcY = 1-(py/H)*2;
      const V = this.camera.viewMatrix();
      const P = this.camera.projMatrix(W/H);
      const invVP = P.mul(V).inverse();
      const near4 = invVP.mulVec4(new Vec4(ndcX, ndcY, -1, 1));
      const far4  = invVP.mulVec4(new Vec4(ndcX, ndcY,  1, 1));
      const nearW = new Vec3(near4.x/near4.w, near4.y/near4.w, near4.z/near4.w);
      const farW  = new Vec3(far4.x/far4.w,  far4.y/far4.w,  far4.z/far4.w);
      return { origin: nearW, dir: farW.sub(nearW).normalize() };
    }

    // Bounding-sphere raycast
    raycastObjects(px, py, W, H) {
      const ray = this.screenRay(px, py, W, H);
      let best = null, bestT = Infinity;
      for (const obj of this.objects) {
        if (!obj.visible) continue;
        const oc = obj.worldCenter().sub(ray.origin);
        const maxR = Math.max(obj.scale.x, obj.scale.y, obj.scale.z) * obj.boundingSphereR;
        const tca = oc.dot(ray.dir);
        const d2  = oc.dot(oc) - tca*tca;
        const r2  = maxR*maxR;
        if (d2 > r2) continue;
        const thc = Math.sqrt(r2 - d2);
        const t = tca - thc;
        if (t > 0 && t < bestT) { bestT = t; best = obj; }
      }
      return best;
    }

    render(canvas) {
      const W = canvas.width, H = canvas.height;
      const rW = Math.max(1, (W / this.renderer.quality) | 0);
      const rH = Math.max(1, (H / this.renderer.quality) | 0);
      if (this.renderer.width !== rW || this.renderer.height !== rH) {
        this.renderer.resize(rW, rH);
      }

      this.renderer.clear();

      const V   = this.camera.viewMatrix();
      const P   = this.camera.projMatrix(rW / rH);
      const VP  = P.mul(V);

      // sort objects back-to-front (painter's fallback) is handled by z-buffer

      for (const obj of this.objects) {
        if (!obj.visible) continue;
        obj.buildWorldGeometry();

        const wv = obj._worldVerts;
        const wn = obj._worldNormals;

        // project all verts
        const sv = wv.map(v => {
          const clip = VP.mulVec4(new Vec4(v.x, v.y, v.z, 1));
          if (clip.w < this.camera.near * 0.5) return null;
          const ndcX = clip.x/clip.w, ndcY = clip.y/clip.w, ndcZ = clip.z/clip.w;
          return { x:(ndcX*0.5+0.5)*rW, y:(1-(ndcY*0.5+0.5))*rH, z:ndcZ };
        });

        for (const tri of obj.geometry.triangles) {
          const [i0, i1, i2] = tri;
          const sp0 = sv[i0], sp1 = sv[i1], sp2 = sv[i2];
          if (!sp0 || !sp1 || !sp2) continue;

          if (obj.material.wireframe) {
            this.renderer.drawWireframeTriangle(
              sp0, sp1, sp2,
              obj.material.r, obj.material.g, obj.material.b
            );
          } else {
            // back-face cull
            const ex = sp1.x-sp0.x, ey = sp1.y-sp0.y;
            const fx = sp2.x-sp0.x, fy = sp2.y-sp0.y;
            if (ex*fy - ey*fx > 0) continue;

            this.renderer.drawTriangle(
              sp0, sp1, sp2,
              wn[i0], wn[i1], wn[i2],
              wv[i0], wv[i1], wv[i2],
              obj.material,
              this.lights,
              this.camera.position
            );
          }
        }
      }

      // blit to main canvas (upscale if quality > 1)
      const ctx = canvas.getContext('2d');
      const imgData = new ImageData(this.renderer.pixels, rW, rH);
      if (this.renderer.quality === 1) {
        ctx.putImageData(imgData, 0, 0);
      } else {
        const tmpCanvas = document.createElement('canvas');
        tmpCanvas.width = rW; tmpCanvas.height = rH;
        tmpCanvas.getContext('2d').putImageData(imgData, 0, 0);
        ctx.imageSmoothingEnabled = false;
        ctx.drawImage(tmpCanvas, 0, 0, W, H);
      }
    }
  }

  // ============================================================
  // §7  OVERLAY CANVAS MANAGER
  // ============================================================

  class OverlayManager {
    constructor() {
      this.canvas  = null;
      this.scene   = new Scene();
      this._loop   = null;
      this._running = false;
    }

    _createCanvas() {
      if (this.canvas) return;
      const stage = document.querySelector('canvas') || document.body;
      const c = document.createElement('canvas');
      c.id     = '__3dcamera_overlay';
      c.style.cssText = [
        'position:absolute', 'top:0', 'left:0',
        'pointer-events:none', 'z-index:9999',
        'width:100%', 'height:100%'
      ].join(';');
      (stage.parentElement || document.body).appendChild(c);
      this.canvas = c;
      this._resize();
      window.addEventListener('resize', () => this._resize());
    }

    _resize() {
      if (!this.canvas) return;
      const p = this.canvas.parentElement;
      this.canvas.width  = p ? p.clientWidth  : window.innerWidth;
      this.canvas.height = p ? p.clientHeight : window.innerHeight;
    }

    startRender() {
      this._createCanvas();
      if (this._running) return;
      this._running = true;
      const loop = () => {
        if (!this._running) return;
        this.scene.render(this.canvas);
        this._loop = requestAnimationFrame(loop);
      };
      loop();
    }

    stopRender() {
      this._running = false;
      if (this._loop) { cancelAnimationFrame(this._loop); this._loop = null; }
      if (this.canvas) {
        const ctx = this.canvas.getContext('2d');
        ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      }
    }

    get width()  { return this.canvas ? this.canvas.width  : 480; }
    get height() { return this.canvas ? this.canvas.height : 360; }
  }

  // ============================================================
  // §8  EXTENSION DEFINITION
  // ============================================================

  const overlay = new OverlayManager();

  class Ext3DCamera {
    constructor(runtime) {
      this.runtime = runtime;
    }

    getInfo() {
      return {
        id: '3Dcamera',
        name: '3D Camera',
        color1: '#1a73e8',
        color2: '#1558b0',
        color3: '#0d3f80',
        blocks: [
          // ── Scene Control ──────────────────────────────
          {
            opcode: 'startRender',
            blockType: Scratch.BlockType.COMMAND,
            text: 'start 3D render'
          },
          {
            opcode: 'stopRender',
            blockType: Scratch.BlockType.COMMAND,
            text: 'stop 3D render'
          },
          {
            opcode: 'clearScene',
            blockType: Scratch.BlockType.COMMAND,
            text: 'clear all objects from scene'
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Camera ──' },
          // ── Camera ────────────────────────────────────
          {
            opcode: 'setCameraPosition',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set camera position x [X] y [Y] z [Z]',
            arguments: {
              X: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y: { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 },
              Z: { type: Scratch.ArgumentType.NUMBER, defaultValue: 5 }
            }
          },
          {
            opcode: 'setCameraRotation',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set camera yaw [YAW] pitch [PITCH] roll [ROLL]',
            arguments: {
              YAW:   { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              PITCH: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              ROLL:  { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'setCameraFOV',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set camera FOV to [FOV] degrees',
            arguments: {
              FOV: { type: Scratch.ArgumentType.NUMBER, defaultValue: 60 }
            }
          },
          {
            opcode: 'moveCameraForward',
            blockType: Scratch.BlockType.COMMAND,
            text: 'move camera forward [DIST] units',
            arguments: {
              DIST: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0.5 }
            }
          },
          {
            opcode: 'moveCameraRight',
            blockType: Scratch.BlockType.COMMAND,
            text: 'move camera right [DIST] units',
            arguments: {
              DIST: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0.5 }
            }
          },
          {
            opcode: 'moveCameraUp',
            blockType: Scratch.BlockType.COMMAND,
            text: 'move camera up [DIST] units',
            arguments: {
              DIST: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0.5 }
            }
          },
          {
            opcode: 'rotateCameraYaw',
            blockType: Scratch.BlockType.COMMAND,
            text: 'rotate camera yaw by [DEG] degrees',
            arguments: {
              DEG: { type: Scratch.ArgumentType.NUMBER, defaultValue: 5 }
            }
          },
          {
            opcode: 'rotateCameraPitch',
            blockType: Scratch.BlockType.COMMAND,
            text: 'rotate camera pitch by [DEG] degrees',
            arguments: {
              DEG: { type: Scratch.ArgumentType.NUMBER, defaultValue: 5 }
            }
          },
          {
            opcode: 'lookAt',
            blockType: Scratch.BlockType.COMMAND,
            text: 'camera look at x [X] y [Y] z [Z]',
            arguments: {
              X: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Z: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'getCameraX', blockType: Scratch.BlockType.REPORTER,
            text: 'camera X'
          },
          {
            opcode: 'getCameraY', blockType: Scratch.BlockType.REPORTER,
            text: 'camera Y'
          },
          {
            opcode: 'getCameraZ', blockType: Scratch.BlockType.REPORTER,
            text: 'camera Z'
          },
          {
            opcode: 'getCameraYaw',   blockType: Scratch.BlockType.REPORTER, text: 'camera yaw'
          },
          {
            opcode: 'getCameraPitch', blockType: Scratch.BlockType.REPORTER, text: 'camera pitch'
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Objects ──' },
          // ── Objects ───────────────────────────────────
          {
            opcode: 'addObject',
            blockType: Scratch.BlockType.COMMAND,
            text: 'add [TYPE] named [NAME] color [COLOR]',
            arguments: {
              TYPE:  {
                type: Scratch.ArgumentType.STRING,
                defaultValue: 'box',
                menu: 'objectTypes'
              },
              NAME:  { type: Scratch.ArgumentType.STRING,  defaultValue: 'cube1' },
              COLOR: { type: Scratch.ArgumentType.COLOR,   defaultValue: '#ff8800' }
            }
          },
          {
            opcode: 'addObjectSize',
            blockType: Scratch.BlockType.COMMAND,
            text: 'add [TYPE] named [NAME] size [S1] [S2] [S3] color [COLOR]',
            arguments: {
              TYPE:  { type: Scratch.ArgumentType.STRING, defaultValue: 'box', menu: 'objectTypes' },
              NAME:  { type: Scratch.ArgumentType.STRING,  defaultValue: 'obj1' },
              S1:    { type: Scratch.ArgumentType.NUMBER,  defaultValue: 1 },
              S2:    { type: Scratch.ArgumentType.NUMBER,  defaultValue: 1 },
              S3:    { type: Scratch.ArgumentType.NUMBER,  defaultValue: 1 },
              COLOR: { type: Scratch.ArgumentType.COLOR,   defaultValue: '#44aaff' }
            }
          },
          {
            opcode: 'setPosition',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] position x [X] y [Y] z [Z]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              X: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Z: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'setRotation',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] rotation x [RX] y [RY] z [RZ]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              RX: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              RY: { type: Scratch.ArgumentType.NUMBER, defaultValue: 45 },
              RZ: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'setScale',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] scale x [SX] y [SY] z [SZ]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              SX: { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 },
              SY: { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 },
              SZ: { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 }
            }
          },
          {
            opcode: 'setObjectColor',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] color to [COLOR]',
            arguments: {
              NAME:  { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              COLOR: { type: Scratch.ArgumentType.COLOR,  defaultValue: '#ff0000' }
            }
          },
          {
            opcode: 'setWireframe',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] wireframe [BOOL]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              BOOL: { type: Scratch.ArgumentType.STRING, defaultValue: 'on', menu: 'onOff' }
            }
          },
          {
            opcode: 'setObjectVisible',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] visible [BOOL]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              BOOL: { type: Scratch.ArgumentType.STRING, defaultValue: 'on', menu: 'onOff' }
            }
          },
          {
            opcode: 'deleteObject',
            blockType: Scratch.BlockType.COMMAND,
            text: 'delete object [NAME]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' }
            }
          },
          {
            opcode: 'setShininess',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] shininess to [S]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              S:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 64 }
            }
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Lights ──' },
          // ── Lights ────────────────────────────────────
          {
            opcode: 'addPointLight',
            blockType: Scratch.BlockType.COMMAND,
            text: 'add point light [NAME] at x [X] y [Y] z [Z] color [COLOR] intensity [I] range [R]',
            arguments: {
              NAME:  { type: Scratch.ArgumentType.STRING, defaultValue: 'light1' },
              X:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 3 },
              Z:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              COLOR: { type: Scratch.ArgumentType.COLOR,  defaultValue: '#ffffff' },
              I:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 },
              R:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 10 }
            }
          },
          {
            opcode: 'addDirectionalLight',
            blockType: Scratch.BlockType.COMMAND,
            text: 'add directional light [NAME] direction x [DX] y [DY] z [DZ] color [COLOR] intensity [I]',
            arguments: {
              NAME:  { type: Scratch.ArgumentType.STRING, defaultValue: 'sun' },
              DX:    { type: Scratch.ArgumentType.NUMBER, defaultValue: -0.5 },
              DY:    { type: Scratch.ArgumentType.NUMBER, defaultValue: -1 },
              DZ:    { type: Scratch.ArgumentType.NUMBER, defaultValue: -0.5 },
              COLOR: { type: Scratch.ArgumentType.COLOR,  defaultValue: '#fffde0' },
              I:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 }
            }
          },
          {
            opcode: 'setLightOnOff',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set light [NAME] [BOOL]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'sun' },
              BOOL: { type: Scratch.ArgumentType.STRING, defaultValue: 'on', menu: 'onOff' }
            }
          },
          {
            opcode: 'setAmbientLight',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set ambient light to [COLOR] strength [S]',
            arguments: {
              COLOR: { type: Scratch.ArgumentType.COLOR,  defaultValue: '#333333' },
              S:     { type: Scratch.ArgumentType.NUMBER, defaultValue: 1 }
            }
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Environment ──' },
          // ── Environment ───────────────────────────────
          {
            opcode: 'setSkyColor',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set sky top [TOP] bottom [BOTTOM]',
            arguments: {
              TOP:    { type: Scratch.ArgumentType.COLOR, defaultValue: '#1e3c72' },
              BOTTOM: { type: Scratch.ArgumentType.COLOR, defaultValue: '#78b4de' }
            }
          },
          {
            opcode: 'setFog',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set fog [BOOL] color [COLOR] near [NEAR] far [FAR]',
            arguments: {
              BOOL:  { type: Scratch.ArgumentType.STRING, defaultValue: 'on', menu: 'onOff' },
              COLOR: { type: Scratch.ArgumentType.COLOR,  defaultValue: '#c8c8c8' },
              NEAR:  { type: Scratch.ArgumentType.NUMBER, defaultValue: 10 },
              FAR:   { type: Scratch.ArgumentType.NUMBER, defaultValue: 50 }
            }
          },
          {
            opcode: 'setRenderQuality',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set render quality [Q]',
            arguments: {
              Q: {
                type: Scratch.ArgumentType.STRING,
                defaultValue: 'medium',
                menu: 'qualities'
              }
            }
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Raycasting & Projection ──' },
          // ── Raycasting & Projection ───────────────────
          {
            opcode: 'raycastAtMouse',
            blockType: Scratch.BlockType.REPORTER,
            text: 'object at mouse cursor'
          },
          {
            opcode: 'raycastAt',
            blockType: Scratch.BlockType.REPORTER,
            text: 'object at screen x [SX] y [SY]',
            arguments: {
              SX: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              SY: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'projectToScreen',
            blockType: Scratch.BlockType.COMMAND,
            text: 'project 3D x [X] y [Y] z [Z] → store screen coords',
            arguments: {
              X: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Z: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'getProjectedX', blockType: Scratch.BlockType.REPORTER, text: 'projected screen X'
          },
          {
            opcode: 'getProjectedY', blockType: Scratch.BlockType.REPORTER, text: 'projected screen Y'
          },
          { blockType: Scratch.BlockType.LABEL, text: '── Utility ──' },
          // ── Utility ───────────────────────────────────
          {
            opcode: 'objectExists',
            blockType: Scratch.BlockType.BOOLEAN,
            text: 'object [NAME] exists?',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' }
            }
          },
          {
            opcode: 'getObjectX',
            blockType: Scratch.BlockType.REPORTER,
            text: '[NAME] position X',
            arguments: { NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' } }
          },
          {
            opcode: 'getObjectY',
            blockType: Scratch.BlockType.REPORTER,
            text: '[NAME] position Y',
            arguments: { NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' } }
          },
          {
            opcode: 'getObjectZ',
            blockType: Scratch.BlockType.REPORTER,
            text: '[NAME] position Z',
            arguments: { NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' } }
          },
          {
            opcode: 'spinObject',
            blockType: Scratch.BlockType.COMMAND,
            text: 'spin [NAME] on Y axis by [DEG] degrees',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              DEG:  { type: Scratch.ArgumentType.NUMBER, defaultValue: 2 }
            }
          },
          {
            opcode: 'distanceBetween',
            blockType: Scratch.BlockType.REPORTER,
            text: 'distance between [A] and [B]',
            arguments: {
              A: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              B: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube2' }
            }
          },
          {
            opcode: 'distanceCameraToObject',
            blockType: Scratch.BlockType.REPORTER,
            text: 'distance from camera to [NAME]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' }
            }
          },
          {
            opcode: 'setObjectOpacity',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set [NAME] opacity [O] (0-100)',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              O:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 100 }
            }
          },
          {
            opcode: 'moveObjectForward',
            blockType: Scratch.BlockType.COMMAND,
            text: 'move [NAME] along camera forward by [DIST]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              DIST: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0.1 }
            }
          },
          {
            opcode: 'setPointLightPosition',
            blockType: Scratch.BlockType.COMMAND,
            text: 'move point light [NAME] to x [X] y [Y] z [Z]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'light1' },
              X:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 },
              Y:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 3 },
              Z:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 0 }
            }
          },
          {
            opcode: 'isObjectVisible',
            blockType: Scratch.BlockType.BOOLEAN,
            text: 'is [NAME] visible?',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' }
            }
          },
          {
            opcode: 'snapCamera',
            blockType: Scratch.BlockType.COMMAND,
            text: 'snap camera behind [NAME] distance [D] height [H]',
            arguments: {
              NAME: { type: Scratch.ArgumentType.STRING, defaultValue: 'cube1' },
              D:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 3 },
              H:    { type: Scratch.ArgumentType.NUMBER, defaultValue: 1.5 }
            }
          },
          {
            opcode: 'setFogExp',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set fog type [TYPE]',
            arguments: {
              TYPE: {
                type: Scratch.ArgumentType.STRING,
                defaultValue: 'linear',
                menu: 'fogTypes'
              }
            }
          },
          {
            opcode: 'deleteAllLights',
            blockType: Scratch.BlockType.COMMAND,
            text: 'delete all lights'
          },
          {
            opcode: 'setCameraClip',
            blockType: Scratch.BlockType.COMMAND,
            text: 'set camera near [NEAR] far [FAR] clip',
            arguments: {
              NEAR: { type: Scratch.ArgumentType.NUMBER, defaultValue: 0.1 },
              FAR:  { type: Scratch.ArgumentType.NUMBER, defaultValue: 500 }
            }
          }
        ],

        menus: {
          objectTypes: {
            acceptReporters: true,
            items: ['box', 'sphere', 'plane', 'cylinder', 'pyramid', 'cone']
          },
          onOff: {
            acceptReporters: false,
            items: ['on', 'off']
          },
          qualities: {
            acceptReporters: false,
            items: [
              { text: 'high (slow)',   value: '1' },
              { text: 'medium',        value: '2' },
              { text: 'low (fast)',    value: '4' },
              { text: 'very low',      value: '6' }
            ]
          },
          fogTypes: {
            acceptReporters: false,
            items: ['linear', 'exponential']
          }
        }
      };
    }

    // ── Scene Control ──────────────────────────────────────
    startRender()     { overlay.startRender(); }
    stopRender()      { overlay.stopRender(); }
    clearScene()      {
      overlay.scene.objects = [];
      overlay.scene.lights  = [];
    }

    // ── Camera ─────────────────────────────────────────────
    setCameraPosition({ X, Y, Z }) {
      overlay.scene.camera.position = new Vec3(+X, +Y, +Z);
    }
    setCameraRotation({ YAW, PITCH, ROLL }) {
      overlay.scene.camera.yaw   = +YAW;
      overlay.scene.camera.pitch = clamp(+PITCH, -89, 89);
      overlay.scene.camera.roll  = +ROLL;
    }
    setCameraFOV({ FOV }) {
      overlay.scene.camera.fov = clamp(+FOV, 10, 170);
    }
    moveCameraForward({ DIST }) { overlay.scene.camera.moveForward(+DIST); }
    moveCameraRight({ DIST })   { overlay.scene.camera.moveRight(+DIST);   }
    moveCameraUp({ DIST })      { overlay.scene.camera.moveUp(+DIST);      }
    rotateCameraYaw({ DEG })    { overlay.scene.camera.yaw   += +DEG; }
    rotateCameraPitch({ DEG })  {
      overlay.scene.camera.pitch = clamp(overlay.scene.camera.pitch + +DEG, -89, 89);
    }
    lookAt({ X, Y, Z }) {
      const cam = overlay.scene.camera;
      const dir = new Vec3(+X, +Y, +Z).sub(cam.position);
      const horizDist = Math.sqrt(dir.x*dir.x + dir.z*dir.z);
      cam.yaw   = Math.atan2(dir.x, -dir.z) / DEG;
      cam.pitch = clamp(-Math.atan2(dir.y, horizDist) / DEG, -89, 89);
    }
    getCameraX()     { return overlay.scene.camera.position.x.toFixed(3); }
    getCameraY()     { return overlay.scene.camera.position.y.toFixed(3); }
    getCameraZ()     { return overlay.scene.camera.position.z.toFixed(3); }
    getCameraYaw()   { return overlay.scene.camera.yaw.toFixed(2);   }
    getCameraPitch() { return overlay.scene.camera.pitch.toFixed(2); }

    // ── Objects ────────────────────────────────────────────
    addObject({ TYPE, NAME, COLOR }) {
      overlay.scene.addObject(String(NAME), String(TYPE), [1,1,1], String(COLOR), 32);
    }
    addObjectSize({ TYPE, NAME, S1, S2, S3, COLOR }) {
      overlay.scene.addObject(String(NAME), String(TYPE), [+S1,+S2,+S3], String(COLOR), 32);
    }
    setPosition({ NAME, X, Y, Z }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) { o.position = new Vec3(+X, +Y, +Z); o._dirty = true; }
    }
    setRotation({ NAME, RX, RY, RZ }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) { o.rotation = new Vec3(+RX, +RY, +RZ); o._dirty = true; }
    }
    setScale({ NAME, SX, SY, SZ }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) { o.scale = new Vec3(+SX, +SY, +SZ); o._dirty = true; }
    }
    setObjectColor({ NAME, COLOR }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) o.material.setColor(String(COLOR));
    }
    setWireframe({ NAME, BOOL }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) o.material.wireframe = (String(BOOL) === 'on');
    }
    setObjectVisible({ NAME, BOOL }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) o.visible = (String(BOOL) === 'on');
    }
    deleteObject({ NAME }) { overlay.scene.removeObject(String(NAME)); }
    setShininess({ NAME, S }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) o.material.shininess = Math.max(1, +S);
    }
    spinObject({ NAME, DEG }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) { o.rotation.y = (o.rotation.y + +DEG) % 360; o._dirty = true; }
    }
    moveObjectForward({ NAME, DIST }) {
      const o = overlay.scene.findObject(String(NAME));
      if (!o) return;
      const f = overlay.scene.camera.forward();
      o.position = o.position.add(f.mul(+DIST));
      o._dirty = true;
    }
    setObjectOpacity({ NAME, O }) {
      const o = overlay.scene.findObject(String(NAME));
      if (o) o.material.opacity = clamp01(+O / 100);
    }
    objectExists({ NAME }) { return !!overlay.scene.findObject(String(NAME)); }
    isObjectVisible({ NAME }) {
      const o = overlay.scene.findObject(String(NAME));
      return !!(o && o.visible);
    }
    getObjectX({ NAME }) {
      const o = overlay.scene.findObject(String(NAME)); return o ? o.position.x.toFixed(3) : '0';
    }
    getObjectY({ NAME }) {
      const o = overlay.scene.findObject(String(NAME)); return o ? o.position.y.toFixed(3) : '0';
    }
    getObjectZ({ NAME }) {
      const o = overlay.scene.findObject(String(NAME)); return o ? o.position.z.toFixed(3) : '0';
    }
    distanceBetween({ A, B }) {
      const oa = overlay.scene.findObject(String(A));
      const ob = overlay.scene.findObject(String(B));
      if (!oa || !ob) return 0;
      return oa.position.sub(ob.position).length().toFixed(3);
    }
    distanceCameraToObject({ NAME }) {
      const o = overlay.scene.findObject(String(NAME));
      if (!o) return 0;
      return overlay.scene.camera.position.sub(o.position).length().toFixed(3);
    }
    snapCamera({ NAME, D, H }) {
      const o = overlay.scene.findObject(String(NAME));
      if (!o) return;
      const cam = overlay.scene.camera;
      const back = new Vec3(
        Math.sin(cam.yaw*DEG), 0, -Math.cos(cam.yaw*DEG)
      );
      cam.position = o.position.sub(back.mul(+D)).add(new Vec3(0, +H, 0));
    }

    // ── Lights ─────────────────────────────────────────────
    addPointLight({ NAME, X, Y, Z, COLOR, I, R }) {
      overlay.scene.lights.push(
        new PointLight(String(NAME), new Vec3(+X, +Y, +Z), String(COLOR), +I, +R)
      );
    }
    addDirectionalLight({ NAME, DX, DY, DZ, COLOR, I }) {
      overlay.scene.lights.push(
        new DirectionalLight(String(NAME), new Vec3(+DX, +DY, +DZ), String(COLOR), +I)
      );
    }
    setLightOnOff({ NAME, BOOL }) {
      const l = overlay.scene.findLight(String(NAME));
      if (l) l.on = (String(BOOL) === 'on');
    }
    setAmbientLight({ COLOR, S }) {
      const c = hexToRgb(String(COLOR));
      const s = +S;
      overlay.scene.renderer.ambient = {
        r: (c.r/255)*s, g: (c.g/255)*s, b: (c.b/255)*s
      };
    }
    setPointLightPosition({ NAME, X, Y, Z }) {
      const l = overlay.scene.findLight(String(NAME));
      if (l && l instanceof PointLight) l.position = new Vec3(+X, +Y, +Z);
    }
    deleteAllLights() { overlay.scene.lights = []; }

    // ── Environment ────────────────────────────────────────
    setSkyColor({ TOP, BOTTOM }) {
      overlay.scene.renderer.skyTop    = hexToRgb(String(TOP));
      overlay.scene.renderer.skyBottom = hexToRgb(String(BOTTOM));
    }
    setFog({ BOOL, COLOR, NEAR, FAR }) {
      const r = overlay.scene.renderer;
      r.fogEnabled = (String(BOOL) === 'on');
      r.fogColor   = hexToRgb(String(COLOR));
      r.fogNear    = +NEAR;
      r.fogFar     = +FAR;
    }
    setFogExp({ TYPE }) {
      overlay.scene.renderer.fogExp = (String(TYPE) === 'exponential');
    }
    setRenderQuality({ Q }) {
      overlay.scene.renderer.quality = Math.max(1, parseInt(Q, 10) || 2);
    }
    setCameraClip({ NEAR, FAR }) {
      overlay.scene.camera.near = Math.max(0.01, +NEAR);
      overlay.scene.camera.far  = Math.max(overlay.scene.camera.near + 1, +FAR);
    }

    // ── Raycasting & Projection ────────────────────────────
    raycastAtMouse() {
      if (!overlay.canvas) return '';
      const rect = overlay.canvas.getBoundingClientRect();
      // runtime mouse position (Scratch coords) → convert
      const mx = this.runtime.ioDevices && this.runtime.ioDevices.mouse
        ? this.runtime.ioDevices.mouse.getScratchX() : 0;
      const my = this.runtime.ioDevices && this.runtime.ioDevices.mouse
        ? this.runtime.ioDevices.mouse.getScratchY() : 0;
      // Scratch coords: center 0,0; x: -240..240; y: -180..180
      const px = (mx + 240) / 480 * overlay.width;
      const py = (180 - my) / 360 * overlay.height;
      const hit = overlay.scene.raycastObjects(px, py, overlay.width, overlay.height);
      overlay.scene.lastHitName = hit ? hit.name : '';
      return overlay.scene.lastHitName;
    }
    raycastAt({ SX, SY }) {
      if (!overlay.canvas) return '';
      const hit = overlay.scene.raycastObjects(+SX, +SY, overlay.width, overlay.height);
      overlay.scene.lastHitName = hit ? hit.name : '';
      return overlay.scene.lastHitName;
    }
    projectToScreen({ X, Y, Z }) {
      if (!overlay.canvas) return;
      const pt = overlay.scene.projectPoint(new Vec3(+X, +Y, +Z), overlay.width, overlay.height);
      if (pt) {
        overlay.scene.lastProjected = pt;
      } else {
        overlay.scene.lastProjected = { x: -9999, y: -9999 };
      }
    }
    getProjectedX() { return overlay.scene.lastProjected.x.toFixed(1); }
    getProjectedY() { return overlay.scene.lastProjected.y.toFixed(1); }
  }

  // ============================================================
  // §9  REGISTER
  // ============================================================
  Scratch.extensions.register(new Ext3DCamera());

})(Scratch);
